from hw1.task1 import print_result
from hw1.task2 import print_result
from hw1.task3 import print_result
from hw1.task4 import print_result
from hw1.task5 import print_result
from hw1.task6 import print_result
from hw1.task7 import print_result
from hw1.task8 import print_result
from hw1.task9 import print_result
from hw1.task10 import print_result
from hw1.task11 import print_result
from hw1.task12 import print_result
from hw1.task13 import print_result
from hw1.task14 import print_result
from hw2.task1 import print_result
from hw2.task2 import print_result
from hw2.task3 import print_result
from hw2.task4 import print_result
from hw2.task5 import print_result
from hw2.task6 import print_result
from hw2.task7 import print_result
from hw2.task8 import print_result
from hw2.task9 import print_result
from hw2.task10 import print_result
from hw3.task1 import print_result
from hw3.task2 import print_result
from hw3.task3 import print_result
from hw3.task4 import print_result
from hw3.task5 import print_result
from hw3.task6 import print_result
from hw3.task7 import print_result
from hw3.task8 import print_result
from hw3.task9 import print_result
from hw3.task10 import print_result

if __name__ == '__main__':
    print_result()
